### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by Rainer-Lang** [pavlospt/FoodSearch#2]
I'm getting this error:
'''java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lifesum.foodsearch/com.lifesum.foodsearch.activities.MainActivity}: java.lang.IllegalArgumentException: Illegal URL: url_endpoint'''

What do I have to use?

**Comment by pavlospt** [comment]
As I said this is an example project. The URL is not valid.
