### ISSUE TITLE
API is not specified

### ISSUE THREAD

**Issue by maxim-pandra** [pavlospt/FoodSearch#3]
Hey, just wondering, is API you using open? and if it is can you explain what it exactly is, and some basic steps to wair it up?

**Comment by pavlospt** [comment]
Hello, the API is not relevant to what this project aims to teach others. The API is just like a regular REST API that produces JSON responses. It is not open. The only open API is the Google Image Search API.

**Comment by maxim-pandra** [comment]
@pavlospt thanks for a quick reply!
I was just hoping to build and see this project on a device. So I guess I should mock this API if I want such thing right? 
Any way thanx for this nice example, it helped a lot!

**Comment by pavlospt** [comment]
Yes unfortunately you have to mock it. The API was not mine, so I could not just include the endpoint. Have a nice day!
